name: hello_workfow
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add x86_64-unknown-linux-musl
      - run: cargo build --release --target=x86_64-unknown-linux-musl
      - uses: SebRollen/toml-action@v1.2.0
        id: read_toml
        with:
          file: 'Cargo.toml'
          field: 'package.version'
      - uses: hkusu/s3-upload-action@v2
        id: upload
        name: upload to s3
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-southeast-1
          aws-bucket: luongtg-bucket
          file-path: 'target/x86_64-unknown-linux-musl/release/cicd'
          bucket-root: 'test-cicd'
          destination-dir: "v${{ steps.read_toml.outputs.value }}"
          output-file-url: true
          public: true
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.read_toml.outputs.value }}
          release_name: v${{ steps.read_toml.outputs.value }}
          body: "Link download: ${{ steps.upload.outputs.file-url }}"
          draft: false
          prerelease: false