name: hello_workfow
on: [push]
jobs:
  print-hello:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -c "print('Hello github action')"